manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/DustVoice
  projects:
    - name: zmk
      remote: DustVoice
      revision: main
      import: app/west.yml
  self:
    path: config
